module.exports = {
  PATIENT_ID: "PATID",
  DATE: "DATE",
  TABLETS_PER_DAY: "TABSPERDAY",
  TABLETS_PRESCRIBED: "TABS",
  CLINICAL_CODE: "CODE",
  DRUG_FAMILY: "FAMILY",
  DRUG_TYPE: "TYPE",
  DOSE: "DOSE",
  INSTRUCTION: "INSTRUCTION",
  TABSPERDAY: "TABSPERDAY",
  IGNORE: "IGNORE"
};
